In [1]:
import pandas as pd
import numpy as np

In [32]:
df = pd.read_csv("Admission_Predict.csv")
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [33]:
df.drop("Serial No.",inplace=True,axis=1)

In [34]:
df.describe()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,0.724350
std,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,0.142609
min,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,0.340000
25%,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,0.640000
50%,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,0.730000
75%,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,0.830000
max,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,0.970000

In [35]:
df.isna().sum()

GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [36]:
df.Research.value_counts()

Research
1    219
0    181
Name: count, dtype: int64

In [38]:
X = df.drop("Chance of Admit ",axis=1)
y = df["Chance of Admit "]

In [23]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [40]:
X_scaled = scaler.fit_transform(X)
X_scaled

array([[0.94      , 0.92857143, 0.75      , ..., 0.875     , 0.91346154,
        1.        ],
       [0.68      , 0.53571429, 0.75      , ..., 0.875     , 0.66346154,
        1.        ],
       [0.52      , 0.42857143, 0.5       , ..., 0.625     , 0.38461538,
        1.        ],
       ...,
       [0.8       , 0.85714286, 0.75      , ..., 0.875     , 0.84935897,
        1.        ],
       [0.44      , 0.39285714, 0.5       , ..., 0.75      , 0.63461538,
        0.        ],
       [0.86      , 0.89285714, 0.75      , ..., 0.75      , 0.91666667,
        1.        ]])

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, test_size = 0.2, random_state = 1)

In [45]:
X_train

array([[0.22      , 0.17857143, 0.25      , ..., 0.5       , 0.34615385,
        1.        ],
       [0.88      , 0.96428571, 1.        , ..., 0.875     , 0.92948718,
        1.        ],
       [0.3       , 0.71428571, 0.5       , ..., 0.625     , 0.59294872,
        0.        ],
       ...,
       [0.7       , 0.53571429, 0.5       , ..., 0.625     , 0.74038462,
        1.        ],
       [0.72      , 0.67857143, 1.        , ..., 0.75      , 0.77884615,
        1.        ],
       [0.2       , 0.46428571, 0.        , ..., 0.25      , 0.32051282,
        0.        ]])

In [46]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()

In [47]:
reg.fit(X_train,y_train)

LinearRegression()

In [48]:
y_pred = reg.predict(X_test)

In [53]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#should be of closer to 0 for a better model
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse) 
mae = mean_absolute_error(y_test, y_pred)

# should be of closer to 1 for a better model
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"R² Score: {r2}")

print(f"Model Intercept: {reg.intercept_}")
print(f"Model Coefficients: {reg.coef_}")

Mean Squared Error (MSE): 0.004442679729994732
Root Mean Squared Error (RMSE): 0.0666534299942226
Mean Absolute Error (MAE): 0.044957798995776795
R² Score: 0.8079043677020106
Model Intercept: 0.35896159387384774
Model Coefficients: [ 0.07556169  0.08807525  0.03297483 -0.02258936  0.08689335  0.35981731
  0.02610078]